version: '3.3'

volumes:
  pg_data:
  static_volume:
 
services:
  db:
    image: postgres:13.10
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
  catalog:
    build: catalog
    env_file: .env.example
    volumes:
      - static_volume:/static
  nginx:
    image: nginx:1.19.3     
    ports:
      - "80:80"
    restart: always  
    volumes:
      - static_volume:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  