#!/bin/bash
docker-compose -f docker-compose.yml up -d
docker-compose -f docker-compose.yml exec catalog python manage.py migrate
docker-compose -f docker-compose.production.yml exec catalog python manage.py collectstatic
docker-compose -f docker-compose.yml exec catalog cp -r /app/collected_static/. /static/static
docker-compose -f docker-compose.yml exec catalog python manage.py loaddata db.json
echo Test the endpoints